# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
#relative_permalinks: true

# Setup
title:               How it's solved
tagline:             "{a developer's blog}"
description:         'problem solving in action'
url:                 http://evgenlozov.github.io/
baseurl:             ''
paginate:            2

# About/contact
author:
  name:              Yevhen Lozov
  url:               https://www.linkedin.com/pub/yevhen-lozov/81/257/454
  email:             jmen7070@gmail.com

# Custom vars
version:             1.0.0
